"""Canonical stage-review registry.

Keep stage-review checker names, reviewer prompt paths, and canonical output
paths in one place so dispatch, conductor planning, and stage gates cannot drift.
"""

from __future__ import annotations

STAGE_CHECKERS: dict[str, list[str]] = {
    "M1S02": ["source_log_validator", "survey_review"],
    "M2S01": ["m2_search_quality"],
    "M2S02": ["m2_migration"],
    "M2S03": ["m2_design_review"],
    "M2S04": ["m2_design_review"],
    "M2S05": ["m2_experiment_design_review"],
    "M3S01": ["m3_main_experiment_design_review"],
    "M3S02": ["m3_dataset_env_review"],
    "M3S03": ["m3_baseline_result_review", "m3_baseline_lock_audit"],
    "M3S04": ["m3_main_result_review"],
    "M3S05": ["m3_result_validation_review"],
    "M4S01": ["m4_findings_audit"],
    "M4S02": ["m4_analysis_design_review", "m4_execution_readiness_review"],
    "M4S03": ["m4_analysis_execution_review"],
    "M5S01": ["m5_prewrite_review"],
    "M5S02": ["m5_outline_style_review"],
    "M5S03": ["m5_intro_relatedwork_review"],
    "M5S04": ["m5_method_figure_review"],
    "M5S05": ["m5_experiments_results_review"],
    "M5S06": ["m5_analysis_discussion_review"],
    "M5S07": ["m5_abstract_conclusion_review"],
    "M5S08": ["build_verifier", "m5_final_compilation_review"],
    "M5S09": ["m5_full_polish_review"],
    "M6S01": ["m6_internal_peer_review", "m6_submission_audit"],
    "M6S02": ["m6_external_submission_review"],
    "M6S03": ["m6_review_parsing_review"],
    "M6S04": ["m6_rebuttal_strategy_review"],
    "M6S05": ["m6_revision_execution_review"],
    "M6S06": ["m6_revision_validation_review"],
}

STAGE_REVIEW_OUTPUTS: dict[str, dict[str, str]] = {
    "M2S01": {"m2_search_quality": "knowledge/reviews/M2S01_search_quality_review.md"},
    "M2S02": {"m2_migration": "knowledge/reviews/M2S02_migration_review.md"},
    "M2S03": {"m2_design_review": "knowledge/reviews/M2S03_design_review.md"},
    "M2S04": {"m2_design_review": "knowledge/reviews/M2S04_design_review.md"},
    "M2S05": {"m2_experiment_design_review": "knowledge/reviews/M2S05_experiment_design_review.md"},
    "M3S01": {"m3_main_experiment_design_review": "knowledge/reviews/M3S01_main_experiment_design_review.md"},
    "M3S02": {"m3_dataset_env_review": "knowledge/reviews/M3S02_dataset_env_review.md"},
    "M3S03": {
        "m3_baseline_result_review": "knowledge/reviews/M3S03_baseline_result_review.md",
        "m3_baseline_lock_audit": "knowledge/reviews/M3S03_baseline_lock_audit.md",
    },
    "M3S04": {"m3_main_result_review": "knowledge/reviews/M3S04_main_result_review.md"},
    "M3S05": {"m3_result_validation_review": "knowledge/reviews/M3S05_result_validation_review.md"},
    "M4S01": {"m4_findings_audit": "knowledge/reviews/M4S01_findings_audit_review.md"},
    "M4S02": {
        "m4_analysis_design_review": "knowledge/reviews/M4S02_analysis_design_review.md",
        "m4_execution_readiness_review": "knowledge/reviews/M4S02_execution_readiness_review.md",
    },
    "M4S03": {"m4_analysis_execution_review": "knowledge/reviews/M4S03_analysis_execution_review.md"},
    "M5S01": {"m5_prewrite_review": "knowledge/reviews/M5S01_prewrite_review.md"},
    "M5S02": {"m5_outline_style_review": "knowledge/reviews/M5S02_outline_style_review.md"},
    "M5S03": {"m5_intro_relatedwork_review": "knowledge/reviews/M5S03_intro_relatedwork_review.md"},
    "M5S04": {"m5_method_figure_review": "knowledge/reviews/M5S04_method_figure_review.md"},
    "M5S05": {"m5_experiments_results_review": "knowledge/reviews/M5S05_experiments_results_review.md"},
    "M5S06": {"m5_analysis_discussion_review": "knowledge/reviews/M5S06_analysis_discussion_review.md"},
    "M5S07": {"m5_abstract_conclusion_review": "knowledge/reviews/M5S07_abstract_conclusion_review.md"},
    "M5S08": {"m5_final_compilation_review": "knowledge/reviews/M5S08_final_compilation_review.md"},
    "M5S09": {"m5_full_polish_review": "knowledge/reviews/M5S09_full_polish_review.md"},
    "M6S01": {
        "m6_internal_peer_review": "knowledge/reviews/M6S01_internal_peer_review.md",
        "m6_submission_audit": "knowledge/reviews/M6S01_submission_audit_review.md",
    },
    "M6S02": {"m6_external_submission_review": "knowledge/reviews/M6S02_external_submission_review.md"},
    "M6S03": {"m6_review_parsing_review": "knowledge/reviews/M6S03_review_parsing_review.md"},
    "M6S04": {"m6_rebuttal_strategy_review": "knowledge/reviews/M6S04_rebuttal_strategy_review.md"},
    "M6S05": {"m6_revision_execution_review": "knowledge/reviews/M6S05_revision_execution_review.md"},
    "M6S06": {"m6_revision_validation_review": "knowledge/reviews/M6S06_revision_validation_review.md"},
}

CHECKER_AGENT_PATHS: dict[str, str] = {
    "source_log_validator": "critic/source_log_validator/AGENT.md",
    "code_review": "critic/code_review/AGENT.md",
    "data_checker": "critic/data_checker/AGENT.md",
    "evidence": "critic/evidence/AGENT.md",
    "build_verifier": "build_verifier/AGENT.md",
    "survey_review": "critic/survey_review/AGENT.md",
    "m2_search_quality": "critic/m2_search_quality/AGENT.md",
    "m2_migration": "critic/m2_migration/AGENT.md",
    "m2_design_review": "critic/m2_design_review/AGENT.md",
    "m2_experiment_design_review": "critic/m2_experiment_design_review/AGENT.md",
    "m3_main_experiment_design_review": "critic/m3_main_experiment_design_review/AGENT.md",
    "m3_dataset_env_review": "critic/m3_dataset_env_review/AGENT.md",
    "m3_baseline_result_review": "critic/m3_baseline_result_review/AGENT.md",
    "m3_baseline_lock_audit": "critic/m3_baseline_lock_audit/AGENT.md",
    "m3_main_result_review": "critic/m3_main_result_review/AGENT.md",
    "m3_result_validation_review": "critic/m3_result_validation_review/AGENT.md",
    "m4_findings_audit": "critic/m4_findings_audit/AGENT.md",
    "m4_analysis_design_review": "critic/m4_analysis_design_review/AGENT.md",
    "m4_execution_readiness_review": "critic/m4_execution_readiness_review/AGENT.md",
    "m4_analysis_execution_review": "critic/m4_analysis_execution_review/AGENT.md",
    "m5_prewrite_review": "critic/m5_stage_review/AGENT.md",
    "m5_outline_style_review": "critic/m5_stage_review/AGENT.md",
    "m5_intro_relatedwork_review": "critic/m5_stage_review/AGENT.md",
    "m5_method_figure_review": "critic/m5_stage_review/AGENT.md",
    "m5_experiments_results_review": "critic/m5_stage_review/AGENT.md",
    "m5_analysis_discussion_review": "critic/m5_stage_review/AGENT.md",
    "m5_abstract_conclusion_review": "critic/m5_stage_review/AGENT.md",
    "m5_full_polish_review": "critic/m5_stage_review/AGENT.md",
    "m5_final_compilation_review": "critic/m5_stage_review/AGENT.md",
    "m6_internal_peer_review": "critic/m6_internal_peer_review/AGENT.md",
    "m6_submission_audit": "critic/m6_stage_review/AGENT.md",
    "m6_external_submission_review": "critic/m6_stage_review/AGENT.md",
    "m6_review_parsing_review": "critic/m6_stage_review/AGENT.md",
    "m6_rebuttal_strategy_review": "critic/m6_stage_review/AGENT.md",
    "m6_revision_execution_review": "critic/m6_stage_review/AGENT.md",
    "m6_revision_validation_review": "critic/m6_stage_review/AGENT.md",
}
